/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package PASSWOR_GENERATOR;

public class Test {
    public void main(String[] args) {
        System.out.println("Am Working");
    }
}
