/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package PASSWOR_GENERATOR;
import java.util.*;
public class Password_Generator {
    public static void main(String[] args) {
    	Scanner input =new Scanner(System.in);
    	int length;
    	
    	System.out.print("ENTER LENGTH OF PASSWORD => ");
    	length=input.nextInt();
    	
    	String validChar="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
		StringBuilder st =new StringBuilder();
		Random rand =new Random();
		while(0<length--) {
			st.append(validChar.charAt(rand.nextInt(validChar.length())));
		}
		System.out.println(st.toString());
    }
}
